using System = System;
using System.Collections.Frozen;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Diagnostics.CodeAnalysis;
using System.Text.Json;
using System.Text.Json.Serialization;
using Telnyx.Sdk.Core;
using Telnyx.Sdk.Exceptions;

namespace Telnyx.Sdk.Models.Calls.Actions;

/// <summary>
/// Messages sent by the model in response to user messages.
/// </summary>
[JsonConverter(typeof(JsonModelConverter<AssistantMessage, AssistantMessageFromRaw>))]
public sealed record class AssistantMessage : JsonModel
{
    /// <summary>
    /// The role of the messages author, in this case `assistant`.
    /// </summary>
    public required ApiEnum<string, AssistantMessageRole> Role {
        get {
            this._rawData.Freeze();
            return this._rawData.GetNotNullClass<ApiEnum<string, AssistantMessageRole>>(
                "role"
            );
        }
        init { this._rawData.Set("role", value); }
    }

    /// <summary>
    /// The contents of the assistant message. Required unless `tool_calls`
    /// </summary>
    public string? Content {
        get {
            this._rawData.Freeze();
            return this._rawData.GetNullableClass<string>(
                "content"
            );
        }
        init {
            if (value == null) {
                return;
            }

            this._rawData.Set("content", value);
        }
    }

    /// <summary>
    /// Metadata to add to the message
    /// </summary>
    public IReadOnlyDictionary<string, JsonElement>? Metadata {
        get {
            this._rawData.Freeze();
            return this._rawData.GetNullableClass<FrozenDictionary<string, JsonElement>>(
                "metadata"
            );
        }
        init {
            if (value == null) {
                return;
            }

            this._rawData.Set<FrozenDictionary<string, JsonElement>?>(
                "metadata",
                value == null ? null : FrozenDictionary.ToFrozenDictionary(value)
            );
        }
    }

    /// <summary>
    /// The tool calls generated by the model, such as function calls.
    /// </summary>
    public IReadOnlyList<ToolCall>? ToolCalls {
        get {
            this._rawData.Freeze();
            return this._rawData.GetNullableStruct<ImmutableArray<ToolCall>>(
                "tool_calls"
            );
        }
        init {
            if (value == null) {
                return;
            }

            this._rawData.Set<ImmutableArray<ToolCall>?>(
                "tool_calls",
                value == null ? null : ImmutableArray.ToImmutableArray(value)
            );
        }
    }

    /// <inheritdoc/>
    public override void Validate()
    {
        this.Role.Validate();
        _ = this.Content;
        _ = this.Metadata;
        foreach (var item in this.ToolCalls ?? [])
        {
            item.Validate();
        }
    }

    public AssistantMessage ()
    {  }

    #pragma warning disable CS8618
    [SetsRequiredMembers]
    public AssistantMessage (AssistantMessage assistantMessage) : base(
        assistantMessage
    )
    {  }
    #pragma warning restore CS8618

    public AssistantMessage (IReadOnlyDictionary<string, JsonElement> rawData)
    { this._rawData = new(rawData); }

    #pragma warning disable CS8618
    [SetsRequiredMembers]
    AssistantMessage (FrozenDictionary<string, JsonElement> rawData)
    { this._rawData = new(rawData); }
    #pragma warning restore CS8618

    /// <inheritdoc cref="AssistantMessageFromRaw.FromRawUnchecked"/>
    public static AssistantMessage FromRawUnchecked(
        IReadOnlyDictionary<string, JsonElement> rawData
    )
    { return new(FrozenDictionary.ToFrozenDictionary(rawData)); }

    [SetsRequiredMembers]
    public AssistantMessage (ApiEnum<string, AssistantMessageRole> role) : this(

    )
    { this.Role = role; }
}

class AssistantMessageFromRaw : IFromRawJson<AssistantMessage>
{
    /// <inheritdoc/>
    public AssistantMessage FromRawUnchecked(
        IReadOnlyDictionary<string, JsonElement> rawData
    )
    =>AssistantMessage.FromRawUnchecked(rawData);
}

/// <summary>
/// The role of the messages author, in this case `assistant`.
/// </summary>
[JsonConverter(typeof(AssistantMessageRoleConverter))]
public enum AssistantMessageRole
{
    Assistant
}sealed class AssistantMessageRoleConverter : JsonConverter<AssistantMessageRole>
{
    public override AssistantMessageRole Read(
        ref Utf8JsonReader reader,
        System::Type typeToConvert,
        JsonSerializerOptions options
    )
    {
        return JsonSerializer.Deserialize<string>(ref reader, options) switch
        {
            "assistant"=>AssistantMessageRole.Assistant,
            _ =>(AssistantMessageRole)(-1)
        };
    }

    public override void Write(
        Utf8JsonWriter writer,
        AssistantMessageRole value,
        JsonSerializerOptions options
    )
    {
        JsonSerializer.Serialize(writer, value switch
        {
            AssistantMessageRole.Assistant=>"assistant",
            _ => throw new TelnyxInvalidDataException(string.Format("Invalid value '{0}' in {1}",
            value,
            nameof(value)))
        }, options);
    }
}/// <summary>
/// A call to a function tool created by the model.
/// </summary>
[JsonConverter(typeof(JsonModelConverter<ToolCall, ToolCallFromRaw>))]
public sealed record class ToolCall : JsonModel
{
    /// <summary>
    /// The ID of the tool call.
    /// </summary>
    public required string ID {
        get {
            this._rawData.Freeze();
            return this._rawData.GetNotNullClass<string>(
                "id"
            );
        }
        init { this._rawData.Set("id", value); }
    }

    /// <summary>
    /// The function that the model called.
    /// </summary>
    public required Function Function {
        get {
            this._rawData.Freeze();
            return this._rawData.GetNotNullClass<Function>(
                "function"
            );
        }
        init { this._rawData.Set("function", value); }
    }

    /// <summary>
    /// The type of the tool. Currently, only `function` is supported.
    /// </summary>
    public required ApiEnum<string, global::Telnyx.Sdk.Models.Calls.Actions.Type> Type {
        get {
            this._rawData.Freeze();
            return this._rawData.GetNotNullClass<ApiEnum<string, global::Telnyx.Sdk.Models.Calls.Actions.Type>>(
                "type"
            );
        }
        init { this._rawData.Set("type", value); }
    }

    /// <inheritdoc/>
    public override void Validate()
    {
        _ = this.ID;
        this.Function.Validate();
        this.Type.Validate();
    }

    public ToolCall ()
    {  }

    #pragma warning disable CS8618
    [SetsRequiredMembers]
    public ToolCall (ToolCall toolCall) : base(toolCall)
    {  }
    #pragma warning restore CS8618

    public ToolCall (IReadOnlyDictionary<string, JsonElement> rawData)
    { this._rawData = new(rawData); }

    #pragma warning disable CS8618
    [SetsRequiredMembers]
    ToolCall (FrozenDictionary<string, JsonElement> rawData)
    { this._rawData = new(rawData); }
    #pragma warning restore CS8618

    /// <inheritdoc cref="ToolCallFromRaw.FromRawUnchecked"/>
    public static ToolCall FromRawUnchecked(
        IReadOnlyDictionary<string, JsonElement> rawData
    )
    { return new(FrozenDictionary.ToFrozenDictionary(rawData)); }
}class ToolCallFromRaw : IFromRawJson<ToolCall>
{
    /// <inheritdoc/>
    public ToolCall FromRawUnchecked(
        IReadOnlyDictionary<string, JsonElement> rawData
    )
    =>ToolCall.FromRawUnchecked(rawData);
}/// <summary>
/// The function that the model called.
/// </summary>
[JsonConverter(typeof(JsonModelConverter<Function, FunctionFromRaw>))]
public sealed record class Function : JsonModel
{
    /// <summary>
    /// The name of the function to call.
    /// </summary>
    public required string Name {
        get {
            this._rawData.Freeze();
            return this._rawData.GetNotNullClass<string>(
                "name"
            );
        }
        init { this._rawData.Set("name", value); }
    }

    /// <inheritdoc/>
    public override void Validate()
    { _ = this.Name; }

    public Function ()
    {  }

    #pragma warning disable CS8618
    [SetsRequiredMembers]
    public Function (Function function) : base(function)
    {  }
    #pragma warning restore CS8618

    public Function (IReadOnlyDictionary<string, JsonElement> rawData)
    { this._rawData = new(rawData); }

    #pragma warning disable CS8618
    [SetsRequiredMembers]
    Function (FrozenDictionary<string, JsonElement> rawData)
    { this._rawData = new(rawData); }
    #pragma warning restore CS8618

    /// <inheritdoc cref="FunctionFromRaw.FromRawUnchecked"/>
    public static Function FromRawUnchecked(
        IReadOnlyDictionary<string, JsonElement> rawData
    )
    { return new(FrozenDictionary.ToFrozenDictionary(rawData)); }

    [SetsRequiredMembers]
    public Function (string name) : this()
    { this.Name = name; }
}class FunctionFromRaw : IFromRawJson<Function>
{
    /// <inheritdoc/>
    public Function FromRawUnchecked(
        IReadOnlyDictionary<string, JsonElement> rawData
    )
    =>Function.FromRawUnchecked(rawData);
}/// <summary>
/// The type of the tool. Currently, only `function` is supported.
/// </summary>
[JsonConverter(typeof(TypeConverter))]
public enum Type
{
    Function
}sealed class TypeConverter : JsonConverter<global::Telnyx.Sdk.Models.Calls.Actions.Type>
{
    public override global::Telnyx.Sdk.Models.Calls.Actions.Type Read(
        ref Utf8JsonReader reader,
        System::Type typeToConvert,
        JsonSerializerOptions options
    )
    {
        return JsonSerializer.Deserialize<string>(ref reader, options) switch
        {
            "function"=>global::Telnyx.Sdk.Models.Calls.Actions.Type.Function,
            _ =>(global::Telnyx.Sdk.Models.Calls.Actions.Type)(-1)
        };
    }

    public override void Write(
        Utf8JsonWriter writer,
        global::Telnyx.Sdk.Models.Calls.Actions.Type value,
        JsonSerializerOptions options
    )
    {
        JsonSerializer.Serialize(writer, value switch
        {
            global::Telnyx.Sdk.Models.Calls.Actions.Type.Function=>"function",
            _ => throw new TelnyxInvalidDataException(string.Format("Invalid value '{0}' in {1}",
            value,
            nameof(value)))
        }, options);
    }
}