using System = System;
using System.Collections.Frozen;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Diagnostics.CodeAnalysis;
using System.Text.Json;
using System.Text.Json.Serialization;
using Telnyx.Sdk.Core;
using Telnyx.Sdk.Exceptions;

namespace Telnyx.Sdk.Models.UacConnections;

/// <summary>
/// Inbound settings that can be supplied when creating or updating a UAC connection.
/// The SIP subdomain fields returned in UAC connection responses are generated by
/// Telnyx and are not accepted as request parameters.
/// </summary>
[JsonConverter(typeof(JsonModelConverter<UacInboundRequest, UacInboundRequestFromRaw>))]
public sealed record class UacInboundRequest : JsonModel
{
    /// <summary>
    /// This setting allows you to set the format with which the caller's number (ANI)
    /// is sent for inbound phone calls.
    /// </summary>
    public ApiEnum<string, UacInboundRequestAniNumberFormat>? AniNumberFormat {
        get {
            this._rawData.Freeze();
            return this._rawData.GetNullableClass<ApiEnum<string, UacInboundRequestAniNumberFormat>>(
                "ani_number_format"
            );
        }
        init {
            if (value == null) {
                return;
            }

            this._rawData.Set("ani_number_format", value);
        }
    }

    /// <summary>
    /// When set, this will limit the total number of inbound calls to phone numbers
    /// associated with this connection.
    /// </summary>
    public long? ChannelLimit {
        get {
            this._rawData.Freeze();
            return this._rawData.GetNullableStruct<long>(
                "channel_limit"
            );
        }
        init {
            if (value == null) {
                return;
            }

            this._rawData.Set("channel_limit", value);
        }
    }

    /// <summary>
    /// Defines the list of codecs that Telnyx will send for inbound calls to a specific
    /// number on your portal account, in priority order. This only works when the
    /// Connection the number is assigned to uses Media Handling mode: default. OPUS
    /// and H.264 codecs are available only when using TCP or TLS transport for SIP.
    /// </summary>
    public IReadOnlyList<string>? Codecs {
        get {
            this._rawData.Freeze();
            return this._rawData.GetNullableStruct<ImmutableArray<string>>(
                "codecs"
            );
        }
        init {
            if (value == null) {
                return;
            }

            this._rawData.Set<ImmutableArray<string>?>(
                "codecs",
                value == null ? null : ImmutableArray.ToImmutableArray(value)
            );
        }
    }

    /// <summary>
    /// Default routing method to be used when a number is associated with the connection.
    /// Must be one of the routing method types or left blank, other values are not allowed.
    /// </summary>
    public ApiEnum<string, UacInboundRequestDefaultRoutingMethod>? DefaultRoutingMethod {
        get {
            this._rawData.Freeze();
            return this._rawData.GetNullableClass<ApiEnum<string, UacInboundRequestDefaultRoutingMethod>>(
                "default_routing_method"
            );
        }
        init {
            if (value == null) {
                return;
            }

            this._rawData.Set("default_routing_method", value);
        }
    }

    public ApiEnum<string, UacInboundRequestDnisNumberFormat>? DnisNumberFormat {
        get {
            this._rawData.Freeze();
            return this._rawData.GetNullableClass<ApiEnum<string, UacInboundRequestDnisNumberFormat>>(
                "dnis_number_format"
            );
        }
        init {
            if (value == null) {
                return;
            }

            this._rawData.Set("dnis_number_format", value);
        }
    }

    /// <summary>
    /// Generate ringback tone through 183 session progress message with early media.
    /// </summary>
    public bool? GenerateRingbackTone {
        get {
            this._rawData.Freeze();
            return this._rawData.GetNullableStruct<bool>(
                "generate_ringback_tone"
            );
        }
        init {
            if (value == null) {
                return;
            }

            this._rawData.Set("generate_ringback_tone", value);
        }
    }

    /// <summary>
    /// When set, inbound phone calls will receive ISUP parameters via SIP headers.
    /// (Only when available and only when using TCP or TLS transport.)
    /// </summary>
    public bool? IsupHeadersEnabled {
        get {
            this._rawData.Freeze();
            return this._rawData.GetNullableStruct<bool>(
                "isup_headers_enabled"
            );
        }
        init {
            if (value == null) {
                return;
            }

            this._rawData.Set("isup_headers_enabled", value);
        }
    }

    /// <summary>
    /// Enable PRACK messages as defined in RFC3262.
    /// </summary>
    public bool? PrackEnabled {
        get {
            this._rawData.Freeze();
            return this._rawData.GetNullableStruct<bool>(
                "prack_enabled"
            );
        }
        init {
            if (value == null) {
                return;
            }

            this._rawData.Set("prack_enabled", value);
        }
    }

    /// <summary>
    /// When enabled the SIP Connection will receive the Identity header with Shaken/Stir
    /// data in the SIP INVITE message of inbound calls, even when using UDP transport.
    /// </summary>
    public bool? ShakenStirEnabled {
        get {
            this._rawData.Freeze();
            return this._rawData.GetNullableStruct<bool>(
                "shaken_stir_enabled"
            );
        }
        init {
            if (value == null) {
                return;
            }

            this._rawData.Set("shaken_stir_enabled", value);
        }
    }

    /// <summary>
    /// When enabled, allows multiple devices to ring simultaneously on incoming calls.
    /// </summary>
    public ApiEnum<string, UacInboundRequestSimultaneousRinging>? SimultaneousRinging {
        get {
            this._rawData.Freeze();
            return this._rawData.GetNullableClass<ApiEnum<string, UacInboundRequestSimultaneousRinging>>(
                "simultaneous_ringing"
            );
        }
        init {
            if (value == null) {
                return;
            }

            this._rawData.Set("simultaneous_ringing", value);
        }
    }

    /// <summary>
    /// Defaults to true.
    /// </summary>
    public bool? SipCompactHeadersEnabled {
        get {
            this._rawData.Freeze();
            return this._rawData.GetNullableStruct<bool>(
                "sip_compact_headers_enabled"
            );
        }
        init {
            if (value == null) {
                return;
            }

            this._rawData.Set("sip_compact_headers_enabled", value);
        }
    }

    /// <summary>
    /// Selects which `sip_region` to receive inbound calls from. If null, the default
    /// region (US) will be used.
    /// </summary>
    public ApiEnum<string, UacInboundRequestSipRegion>? SipRegion {
        get {
            this._rawData.Freeze();
            return this._rawData.GetNullableClass<ApiEnum<string, UacInboundRequestSipRegion>>(
                "sip_region"
            );
        }
        init {
            if (value == null) {
                return;
            }

            this._rawData.Set("sip_region", value);
        }
    }

    /// <summary>
    /// Time(sec) before aborting if connection is not made.
    /// </summary>
    public long? Timeout1xxSecs {
        get {
            this._rawData.Freeze();
            return this._rawData.GetNullableStruct<long>(
                "timeout_1xx_secs"
            );
        }
        init {
            if (value == null) {
                return;
            }

            this._rawData.Set("timeout_1xx_secs", value);
        }
    }

    /// <summary>
    /// Time(sec) before aborting if call is unanswered (min: 1, max: 600).
    /// </summary>
    public long? Timeout2xxSecs {
        get {
            this._rawData.Freeze();
            return this._rawData.GetNullableStruct<long>(
                "timeout_2xx_secs"
            );
        }
        init {
            if (value == null) {
                return;
            }

            this._rawData.Set("timeout_2xx_secs", value);
        }
    }

    /// <inheritdoc/>
    public override void Validate()
    {
        this.AniNumberFormat?.Validate();
        _ = this.ChannelLimit;
        _ = this.Codecs;
        this.DefaultRoutingMethod?.Validate();
        this.DnisNumberFormat?.Validate();
        _ = this.GenerateRingbackTone;
        _ = this.IsupHeadersEnabled;
        _ = this.PrackEnabled;
        _ = this.ShakenStirEnabled;
        this.SimultaneousRinging?.Validate();
        _ = this.SipCompactHeadersEnabled;
        this.SipRegion?.Validate();
        _ = this.Timeout1xxSecs;
        _ = this.Timeout2xxSecs;
    }

    public UacInboundRequest ()
    {  }

    #pragma warning disable CS8618
    [SetsRequiredMembers]
    public UacInboundRequest (UacInboundRequest uacInboundRequest) : base(
        uacInboundRequest
    )
    {  }
    #pragma warning restore CS8618

    public UacInboundRequest (IReadOnlyDictionary<string, JsonElement> rawData)
    { this._rawData = new(rawData); }

    #pragma warning disable CS8618
    [SetsRequiredMembers]
    UacInboundRequest (FrozenDictionary<string, JsonElement> rawData)
    { this._rawData = new(rawData); }
    #pragma warning restore CS8618

    /// <inheritdoc cref="UacInboundRequestFromRaw.FromRawUnchecked"/>
    public static UacInboundRequest FromRawUnchecked(
        IReadOnlyDictionary<string, JsonElement> rawData
    )
    { return new(FrozenDictionary.ToFrozenDictionary(rawData)); }
}

class UacInboundRequestFromRaw : IFromRawJson<UacInboundRequest>
{
    /// <inheritdoc/>
    public UacInboundRequest FromRawUnchecked(
        IReadOnlyDictionary<string, JsonElement> rawData
    )
    =>UacInboundRequest.FromRawUnchecked(rawData);
}

/// <summary>
/// This setting allows you to set the format with which the caller's number (ANI)
/// is sent for inbound phone calls.
/// </summary>
[JsonConverter(typeof(UacInboundRequestAniNumberFormatConverter))]
public enum UacInboundRequestAniNumberFormat
{
    PlusE164, E164, PlusE164National, E164National
}sealed class UacInboundRequestAniNumberFormatConverter : JsonConverter<UacInboundRequestAniNumberFormat>
{
    public override UacInboundRequestAniNumberFormat Read(
        ref Utf8JsonReader reader,
        System::Type typeToConvert,
        JsonSerializerOptions options
    )
    {
        return JsonSerializer.Deserialize<string>(ref reader, options) switch
        {
            "+E.164"=>UacInboundRequestAniNumberFormat.PlusE164,
            "E.164"=>UacInboundRequestAniNumberFormat.E164,
            "+E.164-national"=>UacInboundRequestAniNumberFormat.PlusE164National,
            "E.164-national"=>UacInboundRequestAniNumberFormat.E164National,
            _ =>(UacInboundRequestAniNumberFormat)(-1)
        };
    }

    public override void Write(
        Utf8JsonWriter writer,
        UacInboundRequestAniNumberFormat value,
        JsonSerializerOptions options
    )
    {
        JsonSerializer.Serialize(writer, value switch
        {
            UacInboundRequestAniNumberFormat.PlusE164=>"+E.164",
            UacInboundRequestAniNumberFormat.E164=>"E.164",
            UacInboundRequestAniNumberFormat.PlusE164National=>"+E.164-national",
            UacInboundRequestAniNumberFormat.E164National=>"E.164-national",
            _ => throw new TelnyxInvalidDataException(string.Format("Invalid value '{0}' in {1}",
            value,
            nameof(value)))
        }, options);
    }
}/// <summary>
/// Default routing method to be used when a number is associated with the connection.
/// Must be one of the routing method types or left blank, other values are not allowed.
/// </summary>
[JsonConverter(typeof(UacInboundRequestDefaultRoutingMethodConverter))]
public enum UacInboundRequestDefaultRoutingMethod
{
    Sequential, RoundRobin
}sealed class UacInboundRequestDefaultRoutingMethodConverter : JsonConverter<UacInboundRequestDefaultRoutingMethod>
{
    public override UacInboundRequestDefaultRoutingMethod Read(
        ref Utf8JsonReader reader,
        System::Type typeToConvert,
        JsonSerializerOptions options
    )
    {
        return JsonSerializer.Deserialize<string>(ref reader, options) switch
        {
            "sequential"=>UacInboundRequestDefaultRoutingMethod.Sequential,
            "round-robin"=>UacInboundRequestDefaultRoutingMethod.RoundRobin,
            _ =>(UacInboundRequestDefaultRoutingMethod)(-1)
        };
    }

    public override void Write(
        Utf8JsonWriter writer,
        UacInboundRequestDefaultRoutingMethod value,
        JsonSerializerOptions options
    )
    {
        JsonSerializer.Serialize(writer, value switch
        {
            UacInboundRequestDefaultRoutingMethod.Sequential=>"sequential",
            UacInboundRequestDefaultRoutingMethod.RoundRobin=>"round-robin",
            _ => throw new TelnyxInvalidDataException(string.Format("Invalid value '{0}' in {1}",
            value,
            nameof(value)))
        }, options);
    }
}[JsonConverter(typeof(UacInboundRequestDnisNumberFormatConverter))]
public enum UacInboundRequestDnisNumberFormat
{
    PlusE164, E164, National, SipUsername
}sealed class UacInboundRequestDnisNumberFormatConverter : JsonConverter<UacInboundRequestDnisNumberFormat>
{
    public override UacInboundRequestDnisNumberFormat Read(
        ref Utf8JsonReader reader,
        System::Type typeToConvert,
        JsonSerializerOptions options
    )
    {
        return JsonSerializer.Deserialize<string>(ref reader, options) switch
        {
            "+e164"=>UacInboundRequestDnisNumberFormat.PlusE164,
            "e164"=>UacInboundRequestDnisNumberFormat.E164,
            "national"=>UacInboundRequestDnisNumberFormat.National,
            "sip_username"=>UacInboundRequestDnisNumberFormat.SipUsername,
            _ =>(UacInboundRequestDnisNumberFormat)(-1)
        };
    }

    public override void Write(
        Utf8JsonWriter writer,
        UacInboundRequestDnisNumberFormat value,
        JsonSerializerOptions options
    )
    {
        JsonSerializer.Serialize(writer, value switch
        {
            UacInboundRequestDnisNumberFormat.PlusE164=>"+e164",
            UacInboundRequestDnisNumberFormat.E164=>"e164",
            UacInboundRequestDnisNumberFormat.National=>"national",
            UacInboundRequestDnisNumberFormat.SipUsername=>"sip_username",
            _ => throw new TelnyxInvalidDataException(string.Format("Invalid value '{0}' in {1}",
            value,
            nameof(value)))
        }, options);
    }
}/// <summary>
/// When enabled, allows multiple devices to ring simultaneously on incoming calls.
/// </summary>
[JsonConverter(typeof(UacInboundRequestSimultaneousRingingConverter))]
public enum UacInboundRequestSimultaneousRinging
{
    Disabled, Enabled
}sealed class UacInboundRequestSimultaneousRingingConverter : JsonConverter<UacInboundRequestSimultaneousRinging>
{
    public override UacInboundRequestSimultaneousRinging Read(
        ref Utf8JsonReader reader,
        System::Type typeToConvert,
        JsonSerializerOptions options
    )
    {
        return JsonSerializer.Deserialize<string>(ref reader, options) switch
        {
            "disabled"=>UacInboundRequestSimultaneousRinging.Disabled,
            "enabled"=>UacInboundRequestSimultaneousRinging.Enabled,
            _ =>(UacInboundRequestSimultaneousRinging)(-1)
        };
    }

    public override void Write(
        Utf8JsonWriter writer,
        UacInboundRequestSimultaneousRinging value,
        JsonSerializerOptions options
    )
    {
        JsonSerializer.Serialize(writer, value switch
        {
            UacInboundRequestSimultaneousRinging.Disabled=>"disabled",
            UacInboundRequestSimultaneousRinging.Enabled=>"enabled",
            _ => throw new TelnyxInvalidDataException(string.Format("Invalid value '{0}' in {1}",
            value,
            nameof(value)))
        }, options);
    }
}/// <summary>
/// Selects which `sip_region` to receive inbound calls from. If null, the default
/// region (US) will be used.
/// </summary>
[JsonConverter(typeof(UacInboundRequestSipRegionConverter))]
public enum UacInboundRequestSipRegion
{
    Us, Europe, Australia
}sealed class UacInboundRequestSipRegionConverter : JsonConverter<UacInboundRequestSipRegion>
{
    public override UacInboundRequestSipRegion Read(
        ref Utf8JsonReader reader,
        System::Type typeToConvert,
        JsonSerializerOptions options
    )
    {
        return JsonSerializer.Deserialize<string>(ref reader, options) switch
        {
            "US"=>UacInboundRequestSipRegion.Us,
            "Europe"=>UacInboundRequestSipRegion.Europe,
            "Australia"=>UacInboundRequestSipRegion.Australia,
            _ =>(UacInboundRequestSipRegion)(-1)
        };
    }

    public override void Write(
        Utf8JsonWriter writer,
        UacInboundRequestSipRegion value,
        JsonSerializerOptions options
    )
    {
        JsonSerializer.Serialize(writer, value switch
        {
            UacInboundRequestSipRegion.Us=>"US",
            UacInboundRequestSipRegion.Europe=>"Europe",
            UacInboundRequestSipRegion.Australia=>"Australia",
            _ => throw new TelnyxInvalidDataException(string.Format("Invalid value '{0}' in {1}",
            value,
            nameof(value)))
        }, options);
    }
}