using System.Collections.Frozen;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using System.Text.Json;
using System.Text.Json.Serialization;
using Telnyx.Sdk.Core;

namespace Telnyx.Sdk.Models.MessagingProfiles;

/// <summary>
/// The URL shortener feature allows automatic replacement of URLs that were generated
/// using a public URL shortener service. Some examples include bit.do, bit.ly, goo.gl,
/// ht.ly, is.gd, ow.ly, rebrand.ly, t.co, tiny.cc, and tinyurl.com. Such URLs are
/// replaced with with links generated by Telnyx. The use of custom links can improve
/// branding and message deliverability.
///
/// <para>To disable this feature, set the object field to `null`. </para>
/// </summary>
[JsonConverter(typeof(JsonModelConverter<UrlShortenerSettings, UrlShortenerSettingsFromRaw>))]
public sealed record class UrlShortenerSettings : JsonModel
{
    /// <summary>
    /// One of the domains provided by the Telnyx URL shortener service.
    /// </summary>
    public required string Domain {
        get {
            this._rawData.Freeze();
            return this._rawData.GetNotNullClass<string>(
                "domain"
            );
        }
        init { this._rawData.Set("domain", value); }
    }

    /// <summary>
    /// Optional prefix that can be used to identify your brand, and will appear in
    /// the Telnyx generated URLs after the domain name.
    /// </summary>
    public string? Prefix {
        get {
            this._rawData.Freeze();
            return this._rawData.GetNullableClass<string>(
                "prefix"
            );
        }
        init {
            if (value == null) {
                return;
            }

            this._rawData.Set("prefix", value);
        }
    }

    /// <summary>
    /// Use the link replacement tool only for links that are specifically blacklisted
    /// by Telnyx.
    /// </summary>
    public bool? ReplaceBlacklistOnly {
        get {
            this._rawData.Freeze();
            return this._rawData.GetNullableStruct<bool>(
                "replace_blacklist_only"
            );
        }
        init {
            if (value == null) {
                return;
            }

            this._rawData.Set("replace_blacklist_only", value);
        }
    }

    /// <summary>
    /// Receive webhooks for when your replaced links are clicked. Webhooks are sent
    /// to the webhooks on the messaging profile.
    /// </summary>
    public bool? SendWebhooks {
        get {
            this._rawData.Freeze();
            return this._rawData.GetNullableStruct<bool>(
                "send_webhooks"
            );
        }
        init {
            if (value == null) {
                return;
            }

            this._rawData.Set("send_webhooks", value);
        }
    }

    /// <inheritdoc/>
    public override void Validate()
    {
        _ = this.Domain;
        _ = this.Prefix;
        _ = this.ReplaceBlacklistOnly;
        _ = this.SendWebhooks;
    }

    public UrlShortenerSettings ()
    {  }

    #pragma warning disable CS8618
    [SetsRequiredMembers]
    public UrlShortenerSettings (
        UrlShortenerSettings urlShortenerSettings
    ) : base(urlShortenerSettings)
    {  }
    #pragma warning restore CS8618

    public UrlShortenerSettings (
        IReadOnlyDictionary<string, JsonElement> rawData
    )
    { this._rawData = new(rawData); }

    #pragma warning disable CS8618
    [SetsRequiredMembers]
    UrlShortenerSettings (FrozenDictionary<string, JsonElement> rawData)
    { this._rawData = new(rawData); }
    #pragma warning restore CS8618

    /// <inheritdoc cref="UrlShortenerSettingsFromRaw.FromRawUnchecked"/>
    public static UrlShortenerSettings FromRawUnchecked(
        IReadOnlyDictionary<string, JsonElement> rawData
    )
    { return new(FrozenDictionary.ToFrozenDictionary(rawData)); }

    [SetsRequiredMembers]
    public UrlShortenerSettings (string domain) : this()
    { this.Domain = domain; }
}

class UrlShortenerSettingsFromRaw : IFromRawJson<UrlShortenerSettings>
{
    /// <inheritdoc/>
    public UrlShortenerSettings FromRawUnchecked(
        IReadOnlyDictionary<string, JsonElement> rawData
    )
    =>UrlShortenerSettings.FromRawUnchecked(rawData);
}