using System.Collections.Frozen;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using System.Text.Json;
using System.Text.Json.Serialization;
using Telnyx.Sdk.Core;

namespace Telnyx.Sdk.Models.Messaging10dlc.PartnerCampaigns;

/// <summary>
/// Campaign is generated by the 10DLC registry once the corresponding campaign request
/// is approved. Each campaign is assigned a unique identifier - **campaignId**. Once
/// a campaign is activated, limited information is published to the NetNumber OSR
/// service for consumption by members of the ecosystem. When a campaign is suspended(reversible)
/// or expired(non-reversible), campaign data is deleted from the OSR service. Most
/// attributes of campaignare immutable, including **usecase**, **vertical**, **brandId**
/// and **cspId**.
/// </summary>
[JsonConverter(typeof(JsonModelConverter<PartnerCampaignListSharedByMeResponse, PartnerCampaignListSharedByMeResponseFromRaw>))]
public sealed record class PartnerCampaignListSharedByMeResponse : JsonModel
{
    /// <summary>
    /// Alphanumeric identifier of the brand associated with this campaign.
    /// </summary>
    public required string BrandID {
        get {
            this._rawData.Freeze();
            return this._rawData.GetNotNullClass<string>(
                "brandId"
            );
        }
        init { this._rawData.Set("brandId", value); }
    }

    /// <summary>
    /// Alphanumeric identifier assigned by the registry for a campaign. This identifier
    /// is required by the NetNumber OSR SMS enabling process of 10DLC.
    /// </summary>
    public required string CampaignID {
        get {
            this._rawData.Freeze();
            return this._rawData.GetNotNullClass<string>(
                "campaignId"
            );
        }
        init { this._rawData.Set("campaignId", value); }
    }

    /// <summary>
    /// Campaign usecase. Must be of defined valid types. Use `/10dlc/enum/usecase`
    /// operation to retrieve usecases available for given brand.
    /// </summary>
    public required string Usecase {
        get {
            this._rawData.Freeze();
            return this._rawData.GetNotNullClass<string>(
                "usecase"
            );
        }
        init { this._rawData.Set("usecase", value); }
    }

    /// <summary>
    /// Unix timestamp when campaign was created.
    /// </summary>
    public string? CreateDate {
        get {
            this._rawData.Freeze();
            return this._rawData.GetNullableClass<string>(
                "createDate"
            );
        }
        init {
            if (value == null) {
                return;
            }

            this._rawData.Set("createDate", value);
        }
    }

    /// <summary>
    /// Current campaign status. Possible values: ACTIVE, EXPIRED. A newly created
    /// campaign defaults to ACTIVE status.
    /// </summary>
    public string? Status {
        get {
            this._rawData.Freeze();
            return this._rawData.GetNullableClass<string>(
                "status"
            );
        }
        init {
            if (value == null) {
                return;
            }

            this._rawData.Set("status", value);
        }
    }

    /// <inheritdoc/>
    public override void Validate()
    {
        _ = this.BrandID;
        _ = this.CampaignID;
        _ = this.Usecase;
        _ = this.CreateDate;
        _ = this.Status;
    }

    public PartnerCampaignListSharedByMeResponse ()
    {  }

    #pragma warning disable CS8618
    [SetsRequiredMembers]
    public PartnerCampaignListSharedByMeResponse (
        PartnerCampaignListSharedByMeResponse partnerCampaignListSharedByMeResponse
    ) : base(partnerCampaignListSharedByMeResponse)
    {  }
    #pragma warning restore CS8618

    public PartnerCampaignListSharedByMeResponse (
        IReadOnlyDictionary<string, JsonElement> rawData
    )
    { this._rawData = new(rawData); }

    #pragma warning disable CS8618
    [SetsRequiredMembers]
    PartnerCampaignListSharedByMeResponse (
        FrozenDictionary<string, JsonElement> rawData
    )
    { this._rawData = new(rawData); }
    #pragma warning restore CS8618

    /// <inheritdoc cref="PartnerCampaignListSharedByMeResponseFromRaw.FromRawUnchecked"/>
    public static PartnerCampaignListSharedByMeResponse FromRawUnchecked(
        IReadOnlyDictionary<string, JsonElement> rawData
    )
    { return new(FrozenDictionary.ToFrozenDictionary(rawData)); }
}

class PartnerCampaignListSharedByMeResponseFromRaw : IFromRawJson<PartnerCampaignListSharedByMeResponse>
{
    /// <inheritdoc/>
    public PartnerCampaignListSharedByMeResponse FromRawUnchecked(
        IReadOnlyDictionary<string, JsonElement> rawData
    )
    =>PartnerCampaignListSharedByMeResponse.FromRawUnchecked(rawData);
}