using System = System;
using System.Collections.Frozen;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Diagnostics.CodeAnalysis;
using System.Text.Json;
using System.Text.Json.Serialization;
using Telnyx.Sdk.Core;
using Telnyx.Sdk.Exceptions;

namespace Telnyx.Sdk.Models.Messaging10dlc.PartnerCampaigns;

/// <summary>
/// Campaign is generated by the 10DLC registry once the corresponding campaign request
/// is approved. Each campaign is assigned a unique identifier - **campaignId**. Once
/// a campaign is activated, limited information is published to the NetNumber OSR
/// service for consumption by members of the ecosystem. When a campaign is suspended(reversible)
/// or expired(non-reversible), campaign data is deleted from the OSR service.
/// </summary>
[JsonConverter(typeof(JsonModelConverter<TelnyxDownstreamCampaign, TelnyxDownstreamCampaignFromRaw>))]
public sealed record class TelnyxDownstreamCampaign : JsonModel
{
    /// <summary>
    /// Unique identifier assigned to the brand by the registry.
    /// </summary>
    public required string TcrBrandID {
        get {
            this._rawData.Freeze();
            return this._rawData.GetNotNullClass<string>(
                "tcrBrandId"
            );
        }
        init { this._rawData.Set("tcrBrandId", value); }
    }

    /// <summary>
    /// Unique identifier assigned to the campaign by the registry.
    /// </summary>
    public required string TcrCampaignID {
        get {
            this._rawData.Freeze();
            return this._rawData.GetNotNullClass<string>(
                "tcrCampaignId"
            );
        }
        init { this._rawData.Set("tcrCampaignId", value); }
    }

    /// <summary>
    /// Age gated content in campaign.
    /// </summary>
    public bool? AgeGated {
        get {
            this._rawData.Freeze();
            return this._rawData.GetNullableStruct<bool>(
                "ageGated"
            );
        }
        init {
            if (value == null) {
                return;
            }

            this._rawData.Set("ageGated", value);
        }
    }

    /// <summary>
    /// Number of phone numbers associated with the campaign
    /// </summary>
    public double? AssignedPhoneNumbersCount {
        get {
            this._rawData.Freeze();
            return this._rawData.GetNullableStruct<double>(
                "assignedPhoneNumbersCount"
            );
        }
        init {
            if (value == null) {
                return;
            }

            this._rawData.Set("assignedPhoneNumbersCount", value);
        }
    }

    /// <summary>
    /// Display or marketing name of the brand.
    /// </summary>
    public string? BrandDisplayName {
        get {
            this._rawData.Freeze();
            return this._rawData.GetNullableClass<string>(
                "brandDisplayName"
            );
        }
        init {
            if (value == null) {
                return;
            }

            this._rawData.Set("brandDisplayName", value);
        }
    }

    /// <summary>
    /// Campaign status
    /// </summary>
    public ApiEnum<string, CampaignStatus>? CampaignStatus {
        get {
            this._rawData.Freeze();
            return this._rawData.GetNullableClass<ApiEnum<string, CampaignStatus>>(
                "campaignStatus"
            );
        }
        init {
            if (value == null) {
                return;
            }

            this._rawData.Set("campaignStatus", value);
        }
    }

    /// <summary>
    /// Date and time that the brand was created at.
    /// </summary>
    public string? CreatedAt {
        get {
            this._rawData.Freeze();
            return this._rawData.GetNullableClass<string>(
                "createdAt"
            );
        }
        init {
            if (value == null) {
                return;
            }

            this._rawData.Set("createdAt", value);
        }
    }

    /// <summary>
    /// Summary description of this campaign.
    /// </summary>
    public string? Description {
        get {
            this._rawData.Freeze();
            return this._rawData.GetNullableClass<string>(
                "description"
            );
        }
        init {
            if (value == null) {
                return;
            }

            this._rawData.Set("description", value);
        }
    }

    /// <summary>
    /// Direct lending or loan arrangement.
    /// </summary>
    public bool? DirectLending {
        get {
            this._rawData.Freeze();
            return this._rawData.GetNullableStruct<bool>(
                "directLending"
            );
        }
        init {
            if (value == null) {
                return;
            }

            this._rawData.Set("directLending", value);
        }
    }

    /// <summary>
    /// Does message generated by the campaign include URL link in SMS?
    /// </summary>
    public bool? EmbeddedLink {
        get {
            this._rawData.Freeze();
            return this._rawData.GetNullableStruct<bool>(
                "embeddedLink"
            );
        }
        init {
            if (value == null) {
                return;
            }

            this._rawData.Set("embeddedLink", value);
        }
    }

    /// <summary>
    /// Sample of an embedded link that will be sent to subscribers.
    /// </summary>
    public string? EmbeddedLinkSample {
        get {
            this._rawData.Freeze();
            return this._rawData.GetNullableClass<string>(
                "embeddedLinkSample"
            );
        }
        init {
            if (value == null) {
                return;
            }

            this._rawData.Set("embeddedLinkSample", value);
        }
    }

    /// <summary>
    /// Does message generated by the campaign include phone number in SMS?
    /// </summary>
    public bool? EmbeddedPhone {
        get {
            this._rawData.Freeze();
            return this._rawData.GetNullableStruct<bool>(
                "embeddedPhone"
            );
        }
        init {
            if (value == null) {
                return;
            }

            this._rawData.Set("embeddedPhone", value);
        }
    }

    /// <summary>
    /// Failure reasons if campaign submission failed
    /// </summary>
    public string? FailureReasons {
        get {
            this._rawData.Freeze();
            return this._rawData.GetNullableClass<string>(
                "failureReasons"
            );
        }
        init {
            if (value == null) {
                return;
            }

            this._rawData.Set("failureReasons", value);
        }
    }

    /// <summary>
    /// Subscriber help keywords. Multiple keywords are comma separated without space.
    /// </summary>
    public string? HelpKeywords {
        get {
            this._rawData.Freeze();
            return this._rawData.GetNullableClass<string>(
                "helpKeywords"
            );
        }
        init {
            if (value == null) {
                return;
            }

            this._rawData.Set("helpKeywords", value);
        }
    }

    /// <summary>
    /// Help message of the campaign.
    /// </summary>
    public string? HelpMessage {
        get {
            this._rawData.Freeze();
            return this._rawData.GetNullableClass<string>(
                "helpMessage"
            );
        }
        init {
            if (value == null) {
                return;
            }

            this._rawData.Set("helpMessage", value);
        }
    }

    /// <summary>
    /// Indicates whether the campaign has a T-Mobile number pool ID associated with it.
    /// </summary>
    public bool? IsNumberPoolingEnabled {
        get {
            this._rawData.Freeze();
            return this._rawData.GetNullableStruct<bool>(
                "isNumberPoolingEnabled"
            );
        }
        init {
            if (value == null) {
                return;
            }

            this._rawData.Set("isNumberPoolingEnabled", value);
        }
    }

    /// <summary>
    /// Message flow description.
    /// </summary>
    public string? MessageFlow {
        get {
            this._rawData.Freeze();
            return this._rawData.GetNullableClass<string>(
                "messageFlow"
            );
        }
        init {
            if (value == null) {
                return;
            }

            this._rawData.Set("messageFlow", value);
        }
    }

    /// <summary>
    /// Does campaign utilize pool of phone numbers?
    /// </summary>
    public bool? NumberPool {
        get {
            this._rawData.Freeze();
            return this._rawData.GetNullableStruct<bool>(
                "numberPool"
            );
        }
        init {
            if (value == null) {
                return;
            }

            this._rawData.Set("numberPool", value);
        }
    }

    /// <summary>
    /// Subscriber opt-in keywords. Multiple keywords are comma separated without space.
    /// </summary>
    public string? OptinKeywords {
        get {
            this._rawData.Freeze();
            return this._rawData.GetNullableClass<string>(
                "optinKeywords"
            );
        }
        init {
            if (value == null) {
                return;
            }

            this._rawData.Set("optinKeywords", value);
        }
    }

    /// <summary>
    /// Subscriber opt-in message.
    /// </summary>
    public string? OptinMessage {
        get {
            this._rawData.Freeze();
            return this._rawData.GetNullableClass<string>(
                "optinMessage"
            );
        }
        init {
            if (value == null) {
                return;
            }

            this._rawData.Set("optinMessage", value);
        }
    }

    /// <summary>
    /// Subscriber opt-out keywords. Multiple keywords are comma separated without space.
    /// </summary>
    public string? OptoutKeywords {
        get {
            this._rawData.Freeze();
            return this._rawData.GetNullableClass<string>(
                "optoutKeywords"
            );
        }
        init {
            if (value == null) {
                return;
            }

            this._rawData.Set("optoutKeywords", value);
        }
    }

    /// <summary>
    /// Subscriber opt-out message.
    /// </summary>
    public string? OptoutMessage {
        get {
            this._rawData.Freeze();
            return this._rawData.GetNullableClass<string>(
                "optoutMessage"
            );
        }
        init {
            if (value == null) {
                return;
            }

            this._rawData.Set("optoutMessage", value);
        }
    }

    /// <summary>
    /// Link to the campaign's privacy policy.
    /// </summary>
    public string? PrivacyPolicyLink {
        get {
            this._rawData.Freeze();
            return this._rawData.GetNullableClass<string>(
                "privacyPolicyLink"
            );
        }
        init {
            if (value == null) {
                return;
            }

            this._rawData.Set("privacyPolicyLink", value);
        }
    }

    /// <summary>
    /// Message sample. Some campaign tiers require 1 or more message samples.
    /// </summary>
    public string? Sample1 {
        get {
            this._rawData.Freeze();
            return this._rawData.GetNullableClass<string>(
                "sample1"
            );
        }
        init {
            if (value == null) {
                return;
            }

            this._rawData.Set("sample1", value);
        }
    }

    /// <summary>
    /// Message sample. Some campaign tiers require 2 or more message samples.
    /// </summary>
    public string? Sample2 {
        get {
            this._rawData.Freeze();
            return this._rawData.GetNullableClass<string>(
                "sample2"
            );
        }
        init {
            if (value == null) {
                return;
            }

            this._rawData.Set("sample2", value);
        }
    }

    /// <summary>
    /// Message sample. Some campaign tiers require 3 or more message samples.
    /// </summary>
    public string? Sample3 {
        get {
            this._rawData.Freeze();
            return this._rawData.GetNullableClass<string>(
                "sample3"
            );
        }
        init {
            if (value == null) {
                return;
            }

            this._rawData.Set("sample3", value);
        }
    }

    /// <summary>
    /// Message sample. Some campaign tiers require 4 or more message samples.
    /// </summary>
    public string? Sample4 {
        get {
            this._rawData.Freeze();
            return this._rawData.GetNullableClass<string>(
                "sample4"
            );
        }
        init {
            if (value == null) {
                return;
            }

            this._rawData.Set("sample4", value);
        }
    }

    /// <summary>
    /// Message sample. Some campaign tiers require 5 or more message samples.
    /// </summary>
    public string? Sample5 {
        get {
            this._rawData.Freeze();
            return this._rawData.GetNullableClass<string>(
                "sample5"
            );
        }
        init {
            if (value == null) {
                return;
            }

            this._rawData.Set("sample5", value);
        }
    }

    /// <summary>
    /// Does campaign require subscriber to opt-in before SMS is sent to subscriber?
    /// </summary>
    public bool? SubscriberOptin {
        get {
            this._rawData.Freeze();
            return this._rawData.GetNullableStruct<bool>(
                "subscriberOptin"
            );
        }
        init {
            if (value == null) {
                return;
            }

            this._rawData.Set("subscriberOptin", value);
        }
    }

    /// <summary>
    /// Does campaign support subscriber opt-out keyword(s)?
    /// </summary>
    public bool? SubscriberOptout {
        get {
            this._rawData.Freeze();
            return this._rawData.GetNullableStruct<bool>(
                "subscriberOptout"
            );
        }
        init {
            if (value == null) {
                return;
            }

            this._rawData.Set("subscriberOptout", value);
        }
    }

    /// <summary>
    /// Campaign sub-usecases. Must be of defined valid sub-usecase types. Use `/10dlc/enum/usecase`
    /// operation to retrieve list of valid sub-usecases
    /// </summary>
    public IReadOnlyList<string>? SubUsecases {
        get {
            this._rawData.Freeze();
            return this._rawData.GetNullableStruct<ImmutableArray<string>>(
                "subUsecases"
            );
        }
        init {
            if (value == null) {
                return;
            }

            this._rawData.Set<ImmutableArray<string>?>(
                "subUsecases",
                value == null ? null : ImmutableArray.ToImmutableArray(value)
            );
        }
    }

    /// <summary>
    /// Is terms &amp; conditions accepted?
    /// </summary>
    public bool? TermsAndConditions {
        get {
            this._rawData.Freeze();
            return this._rawData.GetNullableStruct<bool>(
                "termsAndConditions"
            );
        }
        init {
            if (value == null) {
                return;
            }

            this._rawData.Set("termsAndConditions", value);
        }
    }

    /// <summary>
    /// Link to the campaign's terms and conditions.
    /// </summary>
    public string? TermsAndConditionsLink {
        get {
            this._rawData.Freeze();
            return this._rawData.GetNullableClass<string>(
                "termsAndConditionsLink"
            );
        }
        init {
            if (value == null) {
                return;
            }

            this._rawData.Set("termsAndConditionsLink", value);
        }
    }

    /// <summary>
    /// Date and time that the brand was last updated at.
    /// </summary>
    public string? UpdatedAt {
        get {
            this._rawData.Freeze();
            return this._rawData.GetNullableClass<string>(
                "updatedAt"
            );
        }
        init {
            if (value == null) {
                return;
            }

            this._rawData.Set("updatedAt", value);
        }
    }

    /// <summary>
    /// Campaign usecase. Must be of defined valid types. Use `/10dlc/enum/usecase`
    /// operation to retrieve usecases available for given brand.
    /// </summary>
    public string? Usecase {
        get {
            this._rawData.Freeze();
            return this._rawData.GetNullableClass<string>(
                "usecase"
            );
        }
        init {
            if (value == null) {
                return;
            }

            this._rawData.Set("usecase", value);
        }
    }

    /// <summary>
    /// Failover webhook to which campaign status updates are sent.
    /// </summary>
    public string? WebhookFailoverUrl {
        get {
            this._rawData.Freeze();
            return this._rawData.GetNullableClass<string>(
                "webhookFailoverURL"
            );
        }
        init {
            if (value == null) {
                return;
            }

            this._rawData.Set("webhookFailoverURL", value);
        }
    }

    /// <summary>
    /// Webhook to which campaign status updates are sent.
    /// </summary>
    public string? WebhookUrl {
        get {
            this._rawData.Freeze();
            return this._rawData.GetNullableClass<string>(
                "webhookURL"
            );
        }
        init {
            if (value == null) {
                return;
            }

            this._rawData.Set("webhookURL", value);
        }
    }

    /// <inheritdoc/>
    public override void Validate()
    {
        _ = this.TcrBrandID;
        _ = this.TcrCampaignID;
        _ = this.AgeGated;
        _ = this.AssignedPhoneNumbersCount;
        _ = this.BrandDisplayName;
        this.CampaignStatus?.Validate();
        _ = this.CreatedAt;
        _ = this.Description;
        _ = this.DirectLending;
        _ = this.EmbeddedLink;
        _ = this.EmbeddedLinkSample;
        _ = this.EmbeddedPhone;
        _ = this.FailureReasons;
        _ = this.HelpKeywords;
        _ = this.HelpMessage;
        _ = this.IsNumberPoolingEnabled;
        _ = this.MessageFlow;
        _ = this.NumberPool;
        _ = this.OptinKeywords;
        _ = this.OptinMessage;
        _ = this.OptoutKeywords;
        _ = this.OptoutMessage;
        _ = this.PrivacyPolicyLink;
        _ = this.Sample1;
        _ = this.Sample2;
        _ = this.Sample3;
        _ = this.Sample4;
        _ = this.Sample5;
        _ = this.SubscriberOptin;
        _ = this.SubscriberOptout;
        _ = this.SubUsecases;
        _ = this.TermsAndConditions;
        _ = this.TermsAndConditionsLink;
        _ = this.UpdatedAt;
        _ = this.Usecase;
        _ = this.WebhookFailoverUrl;
        _ = this.WebhookUrl;
    }

    public TelnyxDownstreamCampaign ()
    {  }

    #pragma warning disable CS8618
    [SetsRequiredMembers]
    public TelnyxDownstreamCampaign (
        TelnyxDownstreamCampaign telnyxDownstreamCampaign
    ) : base(telnyxDownstreamCampaign)
    {  }
    #pragma warning restore CS8618

    public TelnyxDownstreamCampaign (
        IReadOnlyDictionary<string, JsonElement> rawData
    )
    { this._rawData = new(rawData); }

    #pragma warning disable CS8618
    [SetsRequiredMembers]
    TelnyxDownstreamCampaign (FrozenDictionary<string, JsonElement> rawData)
    { this._rawData = new(rawData); }
    #pragma warning restore CS8618

    /// <inheritdoc cref="TelnyxDownstreamCampaignFromRaw.FromRawUnchecked"/>
    public static TelnyxDownstreamCampaign FromRawUnchecked(
        IReadOnlyDictionary<string, JsonElement> rawData
    )
    { return new(FrozenDictionary.ToFrozenDictionary(rawData)); }
}

class TelnyxDownstreamCampaignFromRaw : IFromRawJson<TelnyxDownstreamCampaign>
{
    /// <inheritdoc/>
    public TelnyxDownstreamCampaign FromRawUnchecked(
        IReadOnlyDictionary<string, JsonElement> rawData
    )
    =>TelnyxDownstreamCampaign.FromRawUnchecked(rawData);
}

/// <summary>
/// Campaign status
/// </summary>
[JsonConverter(typeof(CampaignStatusConverter))]
public enum CampaignStatus
{
    TcrPending,
    TcrSuspended,
    TcrExpired,
    TcrAccepted,
    TcrFailed,
    TelnyxAccepted,
    TelnyxFailed,
    MnoPending,
    MnoAccepted,
    MnoRejected,
    MnoProvisioned,
    MnoProvisioningFailed
}sealed class CampaignStatusConverter : JsonConverter<CampaignStatus>
{
    public override CampaignStatus Read(
        ref Utf8JsonReader reader,
        System::Type typeToConvert,
        JsonSerializerOptions options
    )
    {
        return JsonSerializer.Deserialize<string>(ref reader, options) switch
        {
            "TCR_PENDING"=>CampaignStatus.TcrPending,
            "TCR_SUSPENDED"=>CampaignStatus.TcrSuspended,
            "TCR_EXPIRED"=>CampaignStatus.TcrExpired,
            "TCR_ACCEPTED"=>CampaignStatus.TcrAccepted,
            "TCR_FAILED"=>CampaignStatus.TcrFailed,
            "TELNYX_ACCEPTED"=>CampaignStatus.TelnyxAccepted,
            "TELNYX_FAILED"=>CampaignStatus.TelnyxFailed,
            "MNO_PENDING"=>CampaignStatus.MnoPending,
            "MNO_ACCEPTED"=>CampaignStatus.MnoAccepted,
            "MNO_REJECTED"=>CampaignStatus.MnoRejected,
            "MNO_PROVISIONED"=>CampaignStatus.MnoProvisioned,
            "MNO_PROVISIONING_FAILED"=>CampaignStatus.MnoProvisioningFailed,
            _ =>(CampaignStatus)(-1)
        };
    }

    public override void Write(
        Utf8JsonWriter writer,
        CampaignStatus value,
        JsonSerializerOptions options
    )
    {
        JsonSerializer.Serialize(writer, value switch
        {
            CampaignStatus.TcrPending=>"TCR_PENDING",
            CampaignStatus.TcrSuspended=>"TCR_SUSPENDED",
            CampaignStatus.TcrExpired=>"TCR_EXPIRED",
            CampaignStatus.TcrAccepted=>"TCR_ACCEPTED",
            CampaignStatus.TcrFailed=>"TCR_FAILED",
            CampaignStatus.TelnyxAccepted=>"TELNYX_ACCEPTED",
            CampaignStatus.TelnyxFailed=>"TELNYX_FAILED",
            CampaignStatus.MnoPending=>"MNO_PENDING",
            CampaignStatus.MnoAccepted=>"MNO_ACCEPTED",
            CampaignStatus.MnoRejected=>"MNO_REJECTED",
            CampaignStatus.MnoProvisioned=>"MNO_PROVISIONED",
            CampaignStatus.MnoProvisioningFailed=>"MNO_PROVISIONING_FAILED",
            _ => throw new TelnyxInvalidDataException(string.Format("Invalid value '{0}' in {1}",
            value,
            nameof(value)))
        }, options);
    }
}