using System;
using System.Collections.Frozen;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Diagnostics.CodeAnalysis;
using System.Net.Http;
using System.Text;
using System.Text.Json;
using Telnyx.Sdk.Core;

namespace Telnyx.Sdk.Models.Messaging10dlc.CampaignBuilder;

/// <summary>
/// Before creating a campaign, use the [Qualify By Usecase endpoint](https://developers.telnyx.com/api-reference/campaign/qualify-by-usecase)
/// to ensure that the brand you want to assign a new campaign to is qualified for
/// the desired use case of that campaign. **Please note:** After campaign creation,
/// you'll only be able to edit the campaign's sample messages. Creating a campaign
/// will entail an upfront, non-refundable three month's cost that will depend on
/// the campaign's use case ([see 10DLC Costs section for details](https://developers.telnyx.com/api-reference/campaign/get-campaign-cost)).
///
/// <para>NOTE: Do not inherit from this type outside the SDK unless you're okay with
/// breaking changes in non-major versions. We may add new methods in the future that
/// cause existing derived classes to break.</para>
/// </summary>
public record class CampaignBuilderSubmitParams : ParamsBase
{
    readonly JsonDictionary _rawBodyData = new();public IReadOnlyDictionary<string, JsonElement> RawBodyData {
        get { return this._rawBodyData.Freeze(); }
    }

    /// <summary>
    /// Alphanumeric identifier of the brand associated with this campaign.
    /// </summary>
    public required string BrandID {
        get {
            this._rawBodyData.Freeze();
            return this._rawBodyData.GetNotNullClass<string>(
                "brandId"
            );
        }
        init { this._rawBodyData.Set("brandId", value); }
    }

    /// <summary>
    /// Summary description of this campaign.
    /// </summary>
    public required string Description {
        get {
            this._rawBodyData.Freeze();
            return this._rawBodyData.GetNotNullClass<string>(
                "description"
            );
        }
        init { this._rawBodyData.Set("description", value); }
    }

    /// <summary>
    /// Campaign usecase. Must be of defined valid types. Use `/10dlc/enum/usecase`
    /// operation to retrieve usecases available for given brand.
    /// </summary>
    public required string Usecase {
        get {
            this._rawBodyData.Freeze();
            return this._rawBodyData.GetNotNullClass<string>(
                "usecase"
            );
        }
        init { this._rawBodyData.Set("usecase", value); }
    }

    /// <summary>
    /// Age gated message content in campaign.
    /// </summary>
    public bool? AgeGated {
        get {
            this._rawBodyData.Freeze();
            return this._rawBodyData.GetNullableStruct<bool>(
                "ageGated"
            );
        }
        init {
            if (value == null) {
                return;
            }

            this._rawBodyData.Set("ageGated", value);
        }
    }

    /// <summary>
    /// Campaign subscription auto-renewal option. If set to true, then campaign
    /// will automatically renewal at end of billing cycle.
    /// </summary>
    public bool? AutoRenewal {
        get {
            this._rawBodyData.Freeze();
            return this._rawBodyData.GetNullableStruct<bool>(
                "autoRenewal"
            );
        }
        init {
            if (value == null) {
                return;
            }

            this._rawBodyData.Set("autoRenewal", value);
        }
    }

    /// <summary>
    /// Direct lending or loan arrangement
    /// </summary>
    public bool? DirectLending {
        get {
            this._rawBodyData.Freeze();
            return this._rawBodyData.GetNullableStruct<bool>(
                "directLending"
            );
        }
        init {
            if (value == null) {
                return;
            }

            this._rawBodyData.Set("directLending", value);
        }
    }

    /// <summary>
    /// Does message generated by the campaign include URL link in SMS?
    /// </summary>
    public bool? EmbeddedLink {
        get {
            this._rawBodyData.Freeze();
            return this._rawBodyData.GetNullableStruct<bool>(
                "embeddedLink"
            );
        }
        init {
            if (value == null) {
                return;
            }

            this._rawBodyData.Set("embeddedLink", value);
        }
    }

    /// <summary>
    /// Sample of an embedded link that will be sent to subscribers.
    /// </summary>
    public string? EmbeddedLinkSample {
        get {
            this._rawBodyData.Freeze();
            return this._rawBodyData.GetNullableClass<string>(
                "embeddedLinkSample"
            );
        }
        init {
            if (value == null) {
                return;
            }

            this._rawBodyData.Set("embeddedLinkSample", value);
        }
    }

    /// <summary>
    /// Does message generated by the campaign include phone number in SMS?
    /// </summary>
    public bool? EmbeddedPhone {
        get {
            this._rawBodyData.Freeze();
            return this._rawBodyData.GetNullableStruct<bool>(
                "embeddedPhone"
            );
        }
        init {
            if (value == null) {
                return;
            }

            this._rawBodyData.Set("embeddedPhone", value);
        }
    }

    /// <summary>
    /// Subscriber help keywords. Multiple keywords are comma separated without space.
    /// </summary>
    public string? HelpKeywords {
        get {
            this._rawBodyData.Freeze();
            return this._rawBodyData.GetNullableClass<string>(
                "helpKeywords"
            );
        }
        init {
            if (value == null) {
                return;
            }

            this._rawBodyData.Set("helpKeywords", value);
        }
    }

    /// <summary>
    /// Help message of the campaign.
    /// </summary>
    public string? HelpMessage {
        get {
            this._rawBodyData.Freeze();
            return this._rawBodyData.GetNullableClass<string>(
                "helpMessage"
            );
        }
        init {
            if (value == null) {
                return;
            }

            this._rawBodyData.Set("helpMessage", value);
        }
    }

    /// <summary>
    /// Message flow description.
    /// </summary>
    public string? MessageFlow {
        get {
            this._rawBodyData.Freeze();
            return this._rawBodyData.GetNullableClass<string>(
                "messageFlow"
            );
        }
        init {
            if (value == null) {
                return;
            }

            this._rawBodyData.Set("messageFlow", value);
        }
    }

    /// <summary>
    /// Submit campaign to given list of MNOs by MNO's network ID. Default is all
    /// MNOs if no value provided.
    /// </summary>
    public IReadOnlyList<long>? MnoIds {
        get {
            this._rawBodyData.Freeze();
            return this._rawBodyData.GetNullableStruct<ImmutableArray<long>>(
                "mnoIds"
            );
        }
        init {
            if (value == null) {
                return;
            }

            this._rawBodyData.Set<ImmutableArray<long>?>(
                "mnoIds",
                value == null ? null : ImmutableArray.ToImmutableArray(value)
            );
        }
    }

    /// <summary>
    /// Does campaign utilize pool of phone numbers?
    /// </summary>
    public bool? NumberPool {
        get {
            this._rawBodyData.Freeze();
            return this._rawBodyData.GetNullableStruct<bool>(
                "numberPool"
            );
        }
        init {
            if (value == null) {
                return;
            }

            this._rawBodyData.Set("numberPool", value);
        }
    }

    /// <summary>
    /// Subscriber opt-in keywords. Multiple keywords are comma separated without space.
    /// </summary>
    public string? OptinKeywords {
        get {
            this._rawBodyData.Freeze();
            return this._rawBodyData.GetNullableClass<string>(
                "optinKeywords"
            );
        }
        init {
            if (value == null) {
                return;
            }

            this._rawBodyData.Set("optinKeywords", value);
        }
    }

    /// <summary>
    /// Subscriber opt-in message.
    /// </summary>
    public string? OptinMessage {
        get {
            this._rawBodyData.Freeze();
            return this._rawBodyData.GetNullableClass<string>(
                "optinMessage"
            );
        }
        init {
            if (value == null) {
                return;
            }

            this._rawBodyData.Set("optinMessage", value);
        }
    }

    /// <summary>
    /// Subscriber opt-out keywords. Multiple keywords are comma separated without space.
    /// </summary>
    public string? OptoutKeywords {
        get {
            this._rawBodyData.Freeze();
            return this._rawBodyData.GetNullableClass<string>(
                "optoutKeywords"
            );
        }
        init {
            if (value == null) {
                return;
            }

            this._rawBodyData.Set("optoutKeywords", value);
        }
    }

    /// <summary>
    /// Subscriber opt-out message.
    /// </summary>
    public string? OptoutMessage {
        get {
            this._rawBodyData.Freeze();
            return this._rawBodyData.GetNullableClass<string>(
                "optoutMessage"
            );
        }
        init {
            if (value == null) {
                return;
            }

            this._rawBodyData.Set("optoutMessage", value);
        }
    }

    /// <summary>
    /// Link to the campaign's privacy policy.
    /// </summary>
    public string? PrivacyPolicyLink {
        get {
            this._rawBodyData.Freeze();
            return this._rawBodyData.GetNullableClass<string>(
                "privacyPolicyLink"
            );
        }
        init {
            if (value == null) {
                return;
            }

            this._rawBodyData.Set("privacyPolicyLink", value);
        }
    }

    /// <summary>
    /// Caller supplied campaign reference ID. If supplied, the value must be unique
    /// across all submitted campaigns. Can be used to prevent duplicate campaign registrations.
    /// </summary>
    public string? ReferenceID {
        get {
            this._rawBodyData.Freeze();
            return this._rawBodyData.GetNullableClass<string>(
                "referenceId"
            );
        }
        init {
            if (value == null) {
                return;
            }

            this._rawBodyData.Set("referenceId", value);
        }
    }

    /// <summary>
    /// Alphanumeric identifier of the reseller that you want to associate with this campaign.
    /// </summary>
    public string? ResellerID {
        get {
            this._rawBodyData.Freeze();
            return this._rawBodyData.GetNullableClass<string>(
                "resellerId"
            );
        }
        init {
            if (value == null) {
                return;
            }

            this._rawBodyData.Set("resellerId", value);
        }
    }

    /// <summary>
    /// Message sample. Some campaign tiers require 1 or more message samples.
    /// </summary>
    public string? Sample1 {
        get {
            this._rawBodyData.Freeze();
            return this._rawBodyData.GetNullableClass<string>(
                "sample1"
            );
        }
        init {
            if (value == null) {
                return;
            }

            this._rawBodyData.Set("sample1", value);
        }
    }

    /// <summary>
    /// Message sample. Some campaign tiers require 2 or more message samples.
    /// </summary>
    public string? Sample2 {
        get {
            this._rawBodyData.Freeze();
            return this._rawBodyData.GetNullableClass<string>(
                "sample2"
            );
        }
        init {
            if (value == null) {
                return;
            }

            this._rawBodyData.Set("sample2", value);
        }
    }

    /// <summary>
    /// Message sample. Some campaign tiers require 3 or more message samples.
    /// </summary>
    public string? Sample3 {
        get {
            this._rawBodyData.Freeze();
            return this._rawBodyData.GetNullableClass<string>(
                "sample3"
            );
        }
        init {
            if (value == null) {
                return;
            }

            this._rawBodyData.Set("sample3", value);
        }
    }

    /// <summary>
    /// Message sample. Some campaign tiers require 4 or more message samples.
    /// </summary>
    public string? Sample4 {
        get {
            this._rawBodyData.Freeze();
            return this._rawBodyData.GetNullableClass<string>(
                "sample4"
            );
        }
        init {
            if (value == null) {
                return;
            }

            this._rawBodyData.Set("sample4", value);
        }
    }

    /// <summary>
    /// Message sample. Some campaign tiers require 5 or more message samples.
    /// </summary>
    public string? Sample5 {
        get {
            this._rawBodyData.Freeze();
            return this._rawBodyData.GetNullableClass<string>(
                "sample5"
            );
        }
        init {
            if (value == null) {
                return;
            }

            this._rawBodyData.Set("sample5", value);
        }
    }

    /// <summary>
    /// Does campaign responds to help keyword(s)?
    /// </summary>
    public bool? SubscriberHelp {
        get {
            this._rawBodyData.Freeze();
            return this._rawBodyData.GetNullableStruct<bool>(
                "subscriberHelp"
            );
        }
        init {
            if (value == null) {
                return;
            }

            this._rawBodyData.Set("subscriberHelp", value);
        }
    }

    /// <summary>
    /// Does campaign require subscriber to opt-in before SMS is sent to subscriber?
    /// </summary>
    public bool? SubscriberOptin {
        get {
            this._rawBodyData.Freeze();
            return this._rawBodyData.GetNullableStruct<bool>(
                "subscriberOptin"
            );
        }
        init {
            if (value == null) {
                return;
            }

            this._rawBodyData.Set("subscriberOptin", value);
        }
    }

    /// <summary>
    /// Does campaign support subscriber opt-out keyword(s)?
    /// </summary>
    public bool? SubscriberOptout {
        get {
            this._rawBodyData.Freeze();
            return this._rawBodyData.GetNullableStruct<bool>(
                "subscriberOptout"
            );
        }
        init {
            if (value == null) {
                return;
            }

            this._rawBodyData.Set("subscriberOptout", value);
        }
    }

    /// <summary>
    /// Campaign sub-usecases. Must be of defined valid sub-usecase types. Use `/10dlc/enum/usecase`
    /// operation to retrieve list of valid sub-usecases
    /// </summary>
    public IReadOnlyList<string>? SubUsecases {
        get {
            this._rawBodyData.Freeze();
            return this._rawBodyData.GetNullableStruct<ImmutableArray<string>>(
                "subUsecases"
            );
        }
        init {
            if (value == null) {
                return;
            }

            this._rawBodyData.Set<ImmutableArray<string>?>(
                "subUsecases",
                value == null ? null : ImmutableArray.ToImmutableArray(value)
            );
        }
    }

    /// <summary>
    /// Tags to be set on the Campaign.
    /// </summary>
    public IReadOnlyList<string>? Tag {
        get {
            this._rawBodyData.Freeze();
            return this._rawBodyData.GetNullableStruct<ImmutableArray<string>>(
                "tag"
            );
        }
        init {
            if (value == null) {
                return;
            }

            this._rawBodyData.Set<ImmutableArray<string>?>(
                "tag",
                value == null ? null : ImmutableArray.ToImmutableArray(value)
            );
        }
    }

    /// <summary>
    /// Is terms and conditions accepted?
    /// </summary>
    public bool? TermsAndConditions {
        get {
            this._rawBodyData.Freeze();
            return this._rawBodyData.GetNullableStruct<bool>(
                "termsAndConditions"
            );
        }
        init {
            if (value == null) {
                return;
            }

            this._rawBodyData.Set("termsAndConditions", value);
        }
    }

    /// <summary>
    /// Link to the campaign's terms and conditions.
    /// </summary>
    public string? TermsAndConditionsLink {
        get {
            this._rawBodyData.Freeze();
            return this._rawBodyData.GetNullableClass<string>(
                "termsAndConditionsLink"
            );
        }
        init {
            if (value == null) {
                return;
            }

            this._rawBodyData.Set("termsAndConditionsLink", value);
        }
    }

    /// <summary>
    /// Failover webhook to which campaign status updates are sent.
    /// </summary>
    public string? WebhookFailoverUrl {
        get {
            this._rawBodyData.Freeze();
            return this._rawBodyData.GetNullableClass<string>(
                "webhookFailoverURL"
            );
        }
        init {
            if (value == null) {
                return;
            }

            this._rawBodyData.Set("webhookFailoverURL", value);
        }
    }

    /// <summary>
    /// Webhook to which campaign status updates are sent.
    /// </summary>
    public string? WebhookUrl {
        get {
            this._rawBodyData.Freeze();
            return this._rawBodyData.GetNullableClass<string>(
                "webhookURL"
            );
        }
        init {
            if (value == null) {
                return;
            }

            this._rawBodyData.Set("webhookURL", value);
        }
    }

    public CampaignBuilderSubmitParams ()
    {  }

    #pragma warning disable CS8618
    [SetsRequiredMembers]
    public CampaignBuilderSubmitParams (
        CampaignBuilderSubmitParams campaignBuilderSubmitParams
    ) : base(campaignBuilderSubmitParams)
    { this._rawBodyData = new(campaignBuilderSubmitParams._rawBodyData); }
    #pragma warning restore CS8618

    public CampaignBuilderSubmitParams (
        IReadOnlyDictionary<string, JsonElement> rawHeaderData,
        IReadOnlyDictionary<string, JsonElement> rawQueryData,
        IReadOnlyDictionary<string, JsonElement> rawBodyData
    )
    {
        this._rawHeaderData = new(rawHeaderData);
        this._rawQueryData = new(rawQueryData);
        this._rawBodyData = new(rawBodyData);
    }

    #pragma warning disable CS8618
    [SetsRequiredMembers]
    CampaignBuilderSubmitParams (
        FrozenDictionary<string, JsonElement> rawHeaderData,
        FrozenDictionary<string, JsonElement> rawQueryData,
        FrozenDictionary<string, JsonElement> rawBodyData
    )
    {
        this._rawHeaderData = new(rawHeaderData);
        this._rawQueryData = new(rawQueryData);
        this._rawBodyData = new(rawBodyData);
    }
    #pragma warning restore CS8618

    /// <inheritdoc cref="IFromRawJson{T}.FromRawUnchecked"/>
    public static CampaignBuilderSubmitParams FromRawUnchecked(
        IReadOnlyDictionary<string, JsonElement> rawHeaderData,
        IReadOnlyDictionary<string, JsonElement> rawQueryData,
        IReadOnlyDictionary<string, JsonElement> rawBodyData
    )
    {
        return new(
            FrozenDictionary.ToFrozenDictionary(rawHeaderData),
            FrozenDictionary.ToFrozenDictionary(rawQueryData),
            FrozenDictionary.ToFrozenDictionary(rawBodyData)
        ) ;
    }

    public override string ToString()
    =>JsonSerializer.Serialize(FriendlyJsonPrinter.PrintValue(new Dictionary<string, JsonElement>(

    )
    {
        ["HeaderData"] = FriendlyJsonPrinter.PrintValue(JsonSerializer.SerializeToElement(this._rawHeaderData.Freeze())),
        ["QueryData"] = FriendlyJsonPrinter.PrintValue(JsonSerializer.SerializeToElement(this._rawQueryData.Freeze())),
        ["BodyData"] = FriendlyJsonPrinter.PrintValue(this._rawBodyData.Freeze()),
    }), ModelBase.ToStringSerializerOptions);

    public virtual bool Equals(CampaignBuilderSubmitParams? other)
    {
        if (other == null)
        {
            return false;
        }
        return this._rawHeaderData.Equals(other._rawHeaderData)&&this._rawQueryData.Equals(other._rawQueryData)&&this._rawBodyData.Equals(
            other._rawBodyData
        ) ;
    }

    public override Uri Url(ClientOptions options)
    {
        return this.ResolvePaginationUrl(new UriBuilder(
            options.BaseUrl.ToString().TrimEnd('/') + "/10dlc/campaignBuilder"
        )
        {
            Query = this.QueryString(options, new() { BearerAuth = true })
        }.Uri) ;
    }

    internal override HttpContent? BodyContent()
    {
        return new StringContent(
            JsonSerializer.Serialize(this.RawBodyData, ModelBase.SerializerOptions),
            Encoding.UTF8,
            "application/json"
        ) ;
    }

    internal override void AddHeadersToRequest(
        HttpRequestMessage request, ClientOptions options
    )
    {
        ParamsBase.AddDefaultHeaders(
            request, options, new() { BearerAuth = true }
        );
        foreach (var item in this.RawHeaderData)
        {
            // Explicit per-request headers replace defaults (case-insensitive).
            // Callers own these overrides, including on unauthenticated routes.
            request.Headers.Remove(item.Key);
            ParamsBase.AddHeaderElementToRequest(request, item.Key, item.Value);
        }
    }

    public override int GetHashCode()
    { return 0; }
}